# Generated by Django 4.0.2 on 2022-02-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_alter_visits_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='reason',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
